package Uebung3;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogMessage.proto

// Protobuf Java Version: 3.25.0
public final class LogMessageOuterClass {
  private LogMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Severity}
   */
  public enum Severity
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEBUG = 0;</code>
     */
    DEBUG(0),
    /**
     * <code>INFO = 1;</code>
     */
    INFO(1),
    /**
     * <code>WARN = 2;</code>
     */
    WARN(2),
    /**
     * <code>ERROR = 3;</code>
     */
    ERROR(3),
    /**
     * <code>FATAL = 4;</code>
     */
    FATAL(4),
    ;

    /**
     * <code>DEBUG = 0;</code>
     */
    public static final int DEBUG_VALUE = 0;
    /**
     * <code>INFO = 1;</code>
     */
    public static final int INFO_VALUE = 1;
    /**
     * <code>WARN = 2;</code>
     */
    public static final int WARN_VALUE = 2;
    /**
     * <code>ERROR = 3;</code>
     */
    public static final int ERROR_VALUE = 3;
    /**
     * <code>FATAL = 4;</code>
     */
    public static final int FATAL_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Severity valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Severity forNumber(int value) {
      switch (value) {
        case 0: return DEBUG;
        case 1: return INFO;
        case 2: return WARN;
        case 3: return ERROR;
        case 4: return FATAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Severity>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Severity> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Severity>() {
            public Severity findValueByNumber(int number) {
              return Severity.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return LogMessageOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Severity[] VALUES = values();

    public static Severity valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Severity(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Severity)
  }

  public interface LogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
     * @return Whether the timeCreated field is set.
     */
    boolean hasTimeCreated();
    /**
     * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
     * @return The timeCreated.
     */
    com.google.protobuf.Timestamp getTimeCreated();
    /**
     * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeCreatedOrBuilder();

    /**
     * <code>optional .LogMessage.LogCreator creator = 2;</code>
     * @return Whether the creator field is set.
     */
    boolean hasCreator();
    /**
     * <code>optional .LogMessage.LogCreator creator = 2;</code>
     * @return The creator.
     */
    LogMessageOuterClass.LogMessage.LogCreator getCreator();
    /**
     * <code>optional .LogMessage.LogCreator creator = 2;</code>
     */
    LogMessageOuterClass.LogMessage.LogCreatorOrBuilder getCreatorOrBuilder();

    /**
     * <code>required .Severity severity = 3;</code>
     * @return Whether the severity field is set.
     */
    boolean hasSeverity();
    /**
     * <code>required .Severity severity = 3;</code>
     * @return The severity.
     */
    LogMessageOuterClass.Severity getSeverity();

    /**
     * <code>required string message_body = 4;</code>
     * @return Whether the messageBody field is set.
     */
    boolean hasMessageBody();
    /**
     * <code>required string message_body = 4;</code>
     * @return The messageBody.
     */
    java.lang.String getMessageBody();
    /**
     * <code>required string message_body = 4;</code>
     * @return The bytes for messageBody.
     */
    com.google.protobuf.ByteString
        getMessageBodyBytes();
  }
  /**
   * Protobuf type {@code LogMessage}
   */
  public static final class LogMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LogMessage)
      LogMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogMessage.newBuilder() to construct.
    private LogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogMessage() {
      severity_ = 0;
      messageBody_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogMessageOuterClass.internal_static_LogMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogMessageOuterClass.internal_static_LogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogMessageOuterClass.LogMessage.class, LogMessageOuterClass.LogMessage.Builder.class);
    }

    public interface LogCreatorOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LogMessage.LogCreator)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string creator_name = 1;</code>
       * @return Whether the creatorName field is set.
       */
      boolean hasCreatorName();
      /**
       * <code>required string creator_name = 1;</code>
       * @return The creatorName.
       */
      java.lang.String getCreatorName();
      /**
       * <code>required string creator_name = 1;</code>
       * @return The bytes for creatorName.
       */
      com.google.protobuf.ByteString
          getCreatorNameBytes();

      /**
       * <code>required string location = 2;</code>
       * @return Whether the location field is set.
       */
      boolean hasLocation();
      /**
       * <code>required string location = 2;</code>
       * @return The location.
       */
      java.lang.String getLocation();
      /**
       * <code>required string location = 2;</code>
       * @return The bytes for location.
       */
      com.google.protobuf.ByteString
          getLocationBytes();
    }
    /**
     * Protobuf type {@code LogMessage.LogCreator}
     */
    public static final class LogCreator extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:LogMessage.LogCreator)
        LogCreatorOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use LogCreator.newBuilder() to construct.
      private LogCreator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private LogCreator() {
        creatorName_ = "";
        location_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new LogCreator();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogMessageOuterClass.internal_static_LogMessage_LogCreator_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogMessageOuterClass.internal_static_LogMessage_LogCreator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LogMessageOuterClass.LogMessage.LogCreator.class, LogMessageOuterClass.LogMessage.LogCreator.Builder.class);
      }

      private int bitField0_;
      public static final int CREATOR_NAME_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object creatorName_ = "";
      /**
       * <code>required string creator_name = 1;</code>
       * @return Whether the creatorName field is set.
       */
      @java.lang.Override
      public boolean hasCreatorName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string creator_name = 1;</code>
       * @return The creatorName.
       */
      @java.lang.Override
      public java.lang.String getCreatorName() {
        java.lang.Object ref = creatorName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            creatorName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string creator_name = 1;</code>
       * @return The bytes for creatorName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCreatorNameBytes() {
        java.lang.Object ref = creatorName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creatorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LOCATION_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object location_ = "";
      /**
       * <code>required string location = 2;</code>
       * @return Whether the location field is set.
       */
      @java.lang.Override
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string location = 2;</code>
       * @return The location.
       */
      @java.lang.Override
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            location_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string location = 2;</code>
       * @return The bytes for location.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasCreatorName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLocation()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, creatorName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, location_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, creatorName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, location_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof LogMessageOuterClass.LogMessage.LogCreator)) {
          return super.equals(obj);
        }
        LogMessageOuterClass.LogMessage.LogCreator other = (LogMessageOuterClass.LogMessage.LogCreator) obj;

        if (hasCreatorName() != other.hasCreatorName()) return false;
        if (hasCreatorName()) {
          if (!getCreatorName()
              .equals(other.getCreatorName())) return false;
        }
        if (hasLocation() != other.hasLocation()) return false;
        if (hasLocation()) {
          if (!getLocation()
              .equals(other.getLocation())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCreatorName()) {
          hash = (37 * hash) + CREATOR_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getCreatorName().hashCode();
        }
        if (hasLocation()) {
          hash = (37 * hash) + LOCATION_FIELD_NUMBER;
          hash = (53 * hash) + getLocation().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static LogMessageOuterClass.LogMessage.LogCreator parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static LogMessageOuterClass.LogMessage.LogCreator parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static LogMessageOuterClass.LogMessage.LogCreator parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(LogMessageOuterClass.LogMessage.LogCreator prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code LogMessage.LogCreator}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:LogMessage.LogCreator)
          LogMessageOuterClass.LogMessage.LogCreatorOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return LogMessageOuterClass.internal_static_LogMessage_LogCreator_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return LogMessageOuterClass.internal_static_LogMessage_LogCreator_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  LogMessageOuterClass.LogMessage.LogCreator.class, LogMessageOuterClass.LogMessage.LogCreator.Builder.class);
        }

        // Construct using LogMessageOuterClass.LogMessage.LogCreator.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          creatorName_ = "";
          location_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return LogMessageOuterClass.internal_static_LogMessage_LogCreator_descriptor;
        }

        @java.lang.Override
        public LogMessageOuterClass.LogMessage.LogCreator getDefaultInstanceForType() {
          return LogMessageOuterClass.LogMessage.LogCreator.getDefaultInstance();
        }

        @java.lang.Override
        public LogMessageOuterClass.LogMessage.LogCreator build() {
          LogMessageOuterClass.LogMessage.LogCreator result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public LogMessageOuterClass.LogMessage.LogCreator buildPartial() {
          LogMessageOuterClass.LogMessage.LogCreator result = new LogMessageOuterClass.LogMessage.LogCreator(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(LogMessageOuterClass.LogMessage.LogCreator result) {
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.creatorName_ = creatorName_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.location_ = location_;
            to_bitField0_ |= 0x00000002;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof LogMessageOuterClass.LogMessage.LogCreator) {
            return mergeFrom((LogMessageOuterClass.LogMessage.LogCreator)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(LogMessageOuterClass.LogMessage.LogCreator other) {
          if (other == LogMessageOuterClass.LogMessage.LogCreator.getDefaultInstance()) return this;
          if (other.hasCreatorName()) {
            creatorName_ = other.creatorName_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.hasLocation()) {
            location_ = other.location_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasCreatorName()) {
            return false;
          }
          if (!hasLocation()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  creatorName_ = input.readBytes();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  location_ = input.readBytes();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object creatorName_ = "";
        /**
         * <code>required string creator_name = 1;</code>
         * @return Whether the creatorName field is set.
         */
        public boolean hasCreatorName() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string creator_name = 1;</code>
         * @return The creatorName.
         */
        public java.lang.String getCreatorName() {
          java.lang.Object ref = creatorName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              creatorName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string creator_name = 1;</code>
         * @return The bytes for creatorName.
         */
        public com.google.protobuf.ByteString
            getCreatorNameBytes() {
          java.lang.Object ref = creatorName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            creatorName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string creator_name = 1;</code>
         * @param value The creatorName to set.
         * @return This builder for chaining.
         */
        public Builder setCreatorName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          creatorName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>required string creator_name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCreatorName() {
          creatorName_ = getDefaultInstance().getCreatorName();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>required string creator_name = 1;</code>
         * @param value The bytes for creatorName to set.
         * @return This builder for chaining.
         */
        public Builder setCreatorNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          creatorName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private java.lang.Object location_ = "";
        /**
         * <code>required string location = 2;</code>
         * @return Whether the location field is set.
         */
        public boolean hasLocation() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required string location = 2;</code>
         * @return The location.
         */
        public java.lang.String getLocation() {
          java.lang.Object ref = location_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              location_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string location = 2;</code>
         * @return The bytes for location.
         */
        public com.google.protobuf.ByteString
            getLocationBytes() {
          java.lang.Object ref = location_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            location_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string location = 2;</code>
         * @param value The location to set.
         * @return This builder for chaining.
         */
        public Builder setLocation(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          location_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>required string location = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearLocation() {
          location_ = getDefaultInstance().getLocation();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>required string location = 2;</code>
         * @param value The bytes for location to set.
         * @return This builder for chaining.
         */
        public Builder setLocationBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          location_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:LogMessage.LogCreator)
      }

      // @@protoc_insertion_point(class_scope:LogMessage.LogCreator)
      private static final LogMessageOuterClass.LogMessage.LogCreator DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new LogMessageOuterClass.LogMessage.LogCreator();
      }

      public static LogMessageOuterClass.LogMessage.LogCreator getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<LogCreator>
          PARSER = new com.google.protobuf.AbstractParser<LogCreator>() {
        @java.lang.Override
        public LogCreator parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<LogCreator> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<LogCreator> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public LogMessageOuterClass.LogMessage.LogCreator getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TIMECREATED_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp timeCreated_;
    /**
     * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
     * @return Whether the timeCreated field is set.
     */
    @java.lang.Override
    public boolean hasTimeCreated() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
     * @return The timeCreated.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimeCreated() {
      return timeCreated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeCreated_;
    }
    /**
     * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimeCreatedOrBuilder() {
      return timeCreated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeCreated_;
    }

    public static final int CREATOR_FIELD_NUMBER = 2;
    private LogMessageOuterClass.LogMessage.LogCreator creator_;
    /**
     * <code>optional .LogMessage.LogCreator creator = 2;</code>
     * @return Whether the creator field is set.
     */
    @java.lang.Override
    public boolean hasCreator() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .LogMessage.LogCreator creator = 2;</code>
     * @return The creator.
     */
    @java.lang.Override
    public LogMessageOuterClass.LogMessage.LogCreator getCreator() {
      return creator_ == null ? LogMessageOuterClass.LogMessage.LogCreator.getDefaultInstance() : creator_;
    }
    /**
     * <code>optional .LogMessage.LogCreator creator = 2;</code>
     */
    @java.lang.Override
    public LogMessageOuterClass.LogMessage.LogCreatorOrBuilder getCreatorOrBuilder() {
      return creator_ == null ? LogMessageOuterClass.LogMessage.LogCreator.getDefaultInstance() : creator_;
    }

    public static final int SEVERITY_FIELD_NUMBER = 3;
    private int severity_ = 0;
    /**
     * <code>required .Severity severity = 3;</code>
     * @return Whether the severity field is set.
     */
    @java.lang.Override public boolean hasSeverity() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .Severity severity = 3;</code>
     * @return The severity.
     */
    @java.lang.Override public LogMessageOuterClass.Severity getSeverity() {
      LogMessageOuterClass.Severity result = LogMessageOuterClass.Severity.forNumber(severity_);
      return result == null ? LogMessageOuterClass.Severity.DEBUG : result;
    }

    public static final int MESSAGE_BODY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object messageBody_ = "";
    /**
     * <code>required string message_body = 4;</code>
     * @return Whether the messageBody field is set.
     */
    @java.lang.Override
    public boolean hasMessageBody() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string message_body = 4;</code>
     * @return The messageBody.
     */
    @java.lang.Override
    public java.lang.String getMessageBody() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageBody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message_body = 4;</code>
     * @return The bytes for messageBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBodyBytes() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimeCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeverity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasCreator()) {
        if (!getCreator().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getTimeCreated());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getCreator());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, severity_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageBody_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTimeCreated());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCreator());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, severity_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LogMessageOuterClass.LogMessage)) {
        return super.equals(obj);
      }
      LogMessageOuterClass.LogMessage other = (LogMessageOuterClass.LogMessage) obj;

      if (hasTimeCreated() != other.hasTimeCreated()) return false;
      if (hasTimeCreated()) {
        if (!getTimeCreated()
            .equals(other.getTimeCreated())) return false;
      }
      if (hasCreator() != other.hasCreator()) return false;
      if (hasCreator()) {
        if (!getCreator()
            .equals(other.getCreator())) return false;
      }
      if (hasSeverity() != other.hasSeverity()) return false;
      if (hasSeverity()) {
        if (severity_ != other.severity_) return false;
      }
      if (hasMessageBody() != other.hasMessageBody()) return false;
      if (hasMessageBody()) {
        if (!getMessageBody()
            .equals(other.getMessageBody())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimeCreated()) {
        hash = (37 * hash) + TIMECREATED_FIELD_NUMBER;
        hash = (53 * hash) + getTimeCreated().hashCode();
      }
      if (hasCreator()) {
        hash = (37 * hash) + CREATOR_FIELD_NUMBER;
        hash = (53 * hash) + getCreator().hashCode();
      }
      if (hasSeverity()) {
        hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
        hash = (53 * hash) + severity_;
      }
      if (hasMessageBody()) {
        hash = (37 * hash) + MESSAGE_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getMessageBody().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LogMessageOuterClass.LogMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static LogMessageOuterClass.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static LogMessageOuterClass.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogMessageOuterClass.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LogMessageOuterClass.LogMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogMessage)
        LogMessageOuterClass.LogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogMessageOuterClass.internal_static_LogMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogMessageOuterClass.internal_static_LogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LogMessageOuterClass.LogMessage.class, LogMessageOuterClass.LogMessage.Builder.class);
      }

      // Construct using LogMessageOuterClass.LogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimeCreatedFieldBuilder();
          getCreatorFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timeCreated_ = null;
        if (timeCreatedBuilder_ != null) {
          timeCreatedBuilder_.dispose();
          timeCreatedBuilder_ = null;
        }
        creator_ = null;
        if (creatorBuilder_ != null) {
          creatorBuilder_.dispose();
          creatorBuilder_ = null;
        }
        severity_ = 0;
        messageBody_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LogMessageOuterClass.internal_static_LogMessage_descriptor;
      }

      @java.lang.Override
      public LogMessageOuterClass.LogMessage getDefaultInstanceForType() {
        return LogMessageOuterClass.LogMessage.getDefaultInstance();
      }

      @java.lang.Override
      public LogMessageOuterClass.LogMessage build() {
        LogMessageOuterClass.LogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LogMessageOuterClass.LogMessage buildPartial() {
        LogMessageOuterClass.LogMessage result = new LogMessageOuterClass.LogMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(LogMessageOuterClass.LogMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timeCreated_ = timeCreatedBuilder_ == null
              ? timeCreated_
              : timeCreatedBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.creator_ = creatorBuilder_ == null
              ? creator_
              : creatorBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.severity_ = severity_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.messageBody_ = messageBody_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LogMessageOuterClass.LogMessage) {
          return mergeFrom((LogMessageOuterClass.LogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LogMessageOuterClass.LogMessage other) {
        if (other == LogMessageOuterClass.LogMessage.getDefaultInstance()) return this;
        if (other.hasTimeCreated()) {
          mergeTimeCreated(other.getTimeCreated());
        }
        if (other.hasCreator()) {
          mergeCreator(other.getCreator());
        }
        if (other.hasSeverity()) {
          setSeverity(other.getSeverity());
        }
        if (other.hasMessageBody()) {
          messageBody_ = other.messageBody_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimeCreated()) {
          return false;
        }
        if (!hasSeverity()) {
          return false;
        }
        if (!hasMessageBody()) {
          return false;
        }
        if (hasCreator()) {
          if (!getCreator().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getTimeCreatedFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getCreatorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                int tmpRaw = input.readEnum();
                LogMessageOuterClass.Severity tmpValue =
                    LogMessageOuterClass.Severity.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(3, tmpRaw);
                } else {
                  severity_ = tmpRaw;
                  bitField0_ |= 0x00000004;
                }
                break;
              } // case 24
              case 34: {
                messageBody_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp timeCreated_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeCreatedBuilder_;
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       * @return Whether the timeCreated field is set.
       */
      public boolean hasTimeCreated() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       * @return The timeCreated.
       */
      public com.google.protobuf.Timestamp getTimeCreated() {
        if (timeCreatedBuilder_ == null) {
          return timeCreated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeCreated_;
        } else {
          return timeCreatedBuilder_.getMessage();
        }
      }
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       */
      public Builder setTimeCreated(com.google.protobuf.Timestamp value) {
        if (timeCreatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timeCreated_ = value;
        } else {
          timeCreatedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       */
      public Builder setTimeCreated(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeCreatedBuilder_ == null) {
          timeCreated_ = builderForValue.build();
        } else {
          timeCreatedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       */
      public Builder mergeTimeCreated(com.google.protobuf.Timestamp value) {
        if (timeCreatedBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            timeCreated_ != null &&
            timeCreated_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimeCreatedBuilder().mergeFrom(value);
          } else {
            timeCreated_ = value;
          }
        } else {
          timeCreatedBuilder_.mergeFrom(value);
        }
        if (timeCreated_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       */
      public Builder clearTimeCreated() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeCreated_ = null;
        if (timeCreatedBuilder_ != null) {
          timeCreatedBuilder_.dispose();
          timeCreatedBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeCreatedBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTimeCreatedFieldBuilder().getBuilder();
      }
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeCreatedOrBuilder() {
        if (timeCreatedBuilder_ != null) {
          return timeCreatedBuilder_.getMessageOrBuilder();
        } else {
          return timeCreated_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timeCreated_;
        }
      }
      /**
       * <code>required .google.protobuf.Timestamp timeCreated = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeCreatedFieldBuilder() {
        if (timeCreatedBuilder_ == null) {
          timeCreatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimeCreated(),
                  getParentForChildren(),
                  isClean());
          timeCreated_ = null;
        }
        return timeCreatedBuilder_;
      }

      private LogMessageOuterClass.LogMessage.LogCreator creator_;
      private com.google.protobuf.SingleFieldBuilderV3<
          LogMessageOuterClass.LogMessage.LogCreator, LogMessageOuterClass.LogMessage.LogCreator.Builder, LogMessageOuterClass.LogMessage.LogCreatorOrBuilder> creatorBuilder_;
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       * @return Whether the creator field is set.
       */
      public boolean hasCreator() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       * @return The creator.
       */
      public LogMessageOuterClass.LogMessage.LogCreator getCreator() {
        if (creatorBuilder_ == null) {
          return creator_ == null ? LogMessageOuterClass.LogMessage.LogCreator.getDefaultInstance() : creator_;
        } else {
          return creatorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       */
      public Builder setCreator(LogMessageOuterClass.LogMessage.LogCreator value) {
        if (creatorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          creator_ = value;
        } else {
          creatorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       */
      public Builder setCreator(
          LogMessageOuterClass.LogMessage.LogCreator.Builder builderForValue) {
        if (creatorBuilder_ == null) {
          creator_ = builderForValue.build();
        } else {
          creatorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       */
      public Builder mergeCreator(LogMessageOuterClass.LogMessage.LogCreator value) {
        if (creatorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            creator_ != null &&
            creator_ != LogMessageOuterClass.LogMessage.LogCreator.getDefaultInstance()) {
            getCreatorBuilder().mergeFrom(value);
          } else {
            creator_ = value;
          }
        } else {
          creatorBuilder_.mergeFrom(value);
        }
        if (creator_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       */
      public Builder clearCreator() {
        bitField0_ = (bitField0_ & ~0x00000002);
        creator_ = null;
        if (creatorBuilder_ != null) {
          creatorBuilder_.dispose();
          creatorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       */
      public LogMessageOuterClass.LogMessage.LogCreator.Builder getCreatorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCreatorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       */
      public LogMessageOuterClass.LogMessage.LogCreatorOrBuilder getCreatorOrBuilder() {
        if (creatorBuilder_ != null) {
          return creatorBuilder_.getMessageOrBuilder();
        } else {
          return creator_ == null ?
              LogMessageOuterClass.LogMessage.LogCreator.getDefaultInstance() : creator_;
        }
      }
      /**
       * <code>optional .LogMessage.LogCreator creator = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          LogMessageOuterClass.LogMessage.LogCreator, LogMessageOuterClass.LogMessage.LogCreator.Builder, LogMessageOuterClass.LogMessage.LogCreatorOrBuilder> 
          getCreatorFieldBuilder() {
        if (creatorBuilder_ == null) {
          creatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              LogMessageOuterClass.LogMessage.LogCreator, LogMessageOuterClass.LogMessage.LogCreator.Builder, LogMessageOuterClass.LogMessage.LogCreatorOrBuilder>(
                  getCreator(),
                  getParentForChildren(),
                  isClean());
          creator_ = null;
        }
        return creatorBuilder_;
      }

      private int severity_ = 0;
      /**
       * <code>required .Severity severity = 3;</code>
       * @return Whether the severity field is set.
       */
      @java.lang.Override public boolean hasSeverity() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .Severity severity = 3;</code>
       * @return The severity.
       */
      @java.lang.Override
      public LogMessageOuterClass.Severity getSeverity() {
        LogMessageOuterClass.Severity result = LogMessageOuterClass.Severity.forNumber(severity_);
        return result == null ? LogMessageOuterClass.Severity.DEBUG : result;
      }
      /**
       * <code>required .Severity severity = 3;</code>
       * @param value The severity to set.
       * @return This builder for chaining.
       */
      public Builder setSeverity(LogMessageOuterClass.Severity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        severity_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Severity severity = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeverity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        severity_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object messageBody_ = "";
      /**
       * <code>required string message_body = 4;</code>
       * @return Whether the messageBody field is set.
       */
      public boolean hasMessageBody() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string message_body = 4;</code>
       * @return The messageBody.
       */
      public java.lang.String getMessageBody() {
        java.lang.Object ref = messageBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageBody_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message_body = 4;</code>
       * @return The bytes for messageBody.
       */
      public com.google.protobuf.ByteString
          getMessageBodyBytes() {
        java.lang.Object ref = messageBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message_body = 4;</code>
       * @param value The messageBody to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBody(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        messageBody_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required string message_body = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageBody() {
        messageBody_ = getDefaultInstance().getMessageBody();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>required string message_body = 4;</code>
       * @param value The bytes for messageBody to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        messageBody_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LogMessage)
    }

    // @@protoc_insertion_point(class_scope:LogMessage)
    private static final LogMessageOuterClass.LogMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogMessageOuterClass.LogMessage();
    }

    public static LogMessageOuterClass.LogMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LogMessage>
        PARSER = new com.google.protobuf.AbstractParser<LogMessage>() {
      @java.lang.Override
      public LogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LogMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LogMessageOuterClass.LogMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogMessage_LogCreator_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogMessage_LogCreator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020LogMessage.proto\032\037google/protobuf/time" +
      "stamp.proto\"\317\001\n\nLogMessage\022/\n\013timeCreate" +
      "d\030\001 \002(\0132\032.google.protobuf.Timestamp\022\'\n\007c" +
      "reator\030\002 \001(\0132\026.LogMessage.LogCreator\022\033\n\010" +
      "severity\030\003 \002(\0162\t.Severity\022\024\n\014message_bod" +
      "y\030\004 \002(\t\0324\n\nLogCreator\022\024\n\014creator_name\030\001 " +
      "\002(\t\022\020\n\010location\030\002 \002(\t*?\n\010Severity\022\t\n\005DEB" +
      "UG\020\000\022\010\n\004INFO\020\001\022\010\n\004WARN\020\002\022\t\n\005ERROR\020\003\022\t\n\005F" +
      "ATAL\020\004"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogMessage_descriptor,
        new java.lang.String[] { "TimeCreated", "Creator", "Severity", "MessageBody", });
    internal_static_LogMessage_LogCreator_descriptor =
      internal_static_LogMessage_descriptor.getNestedTypes().get(0);
    internal_static_LogMessage_LogCreator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogMessage_LogCreator_descriptor,
        new java.lang.String[] { "CreatorName", "Location", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
